### PR TITLE
ENG-100 changed all lagotto db{name,user} with alm

### PR DESCRIPTION
**Pull request by evarghese**

### CODE REVIEW

**Review by JackLaBarba — COMMENTED** [review]
These changes look good to me, but what's the plan for rolling them out? It seems like there needs to be some manual migration steps accompanying this, since as-is, this will create new empty db called `alm` but wont ensure any of the existing data is moved into it.

It seems like there needs to be some downtime while we copy the data from the old db to the new one. Or maybe you're planning on manually renaming the db right before these state changes are made?

**Comment by evarghese** [comment]
this would have to be done at dev only, since prod and stage are already using `alm` see [line 61](https://github.com/PLOS-Formulas/lagotto-formula/blob/7a5905a282e8fe48c675ee9e31b388aeee474031/lagotto/map.jinja#L61), downtime associated with dev is ok imho, the sideeffect of this is that we can delete the dev instance in aws since this satisfies the issue of dev matching stage/prod.

**Comment by JackLaBarba** [comment]
> this would have to be done at dev only

Ah right, it's just for dev. I agree that downtime is no problemo there. 

Would you mind deleting L61 and L75 https://github.com/PLOS-Formulas/lagotto-formula/blob/7a5905a282e8fe48c675ee9e31b388aeee474031/lagotto/map.jinja#L75 then? There's no use in overriding the property if it's the same in all envs. Doing so obscures the fact that it's invariant.

**Comment by evarghese** [comment]
> > this would have to be done at dev only
> 
> Ah right, it's just for dev. I agree that downtime is no problemo there.
> 
> Would you mind deleting L61 and L75
> 
> https://github.com/PLOS-Formulas/lagotto-formula/blob/7a5905a282e8fe48c675ee9e31b388aeee474031/lagotto/map.jinja#L75
> then? There's no use in overriding the property if it's the same in all envs. Doing so obscures the fact that it's invariant.

Makes sense to me! will do and merge.

**Pull request merged**
