### PR TITLE
ALM-1045 discover couchdb via consul

### PR DESCRIPTION
**Pull request by JackLaBarba**
And got rid of the 127.0.0.1 fallback since that will never work inside a container

### CODE REVIEW

**Comment by JackLaBarba** [comment]
@sgatchell sorry that I'm pelting you with all these small PRs, this should be the last one.

**Review by sgatchell — APPROVED** [review]
Looks reasonable.  I don't quite understand the role of the tildes in the line being replaced, but maybe that's why this PR exists.

:shipit:

**Comment by sgatchell** [comment]
nvm, a little after-the-fact googling set me straight: 
> You can use + if you know all the values are strings. Jinja also provides the ~ operator, which will ensure all values are converted to string first.

**Comment by JackLaBarba** [comment]
Indeed, it's Jinja's string concat operator. This gist of this PR is that I don't want to use the couchdb url that's hardcoded in the Pillar repo anymore (for example https://github.com/PLOS/molten-pillar/blob/24a2c557d6349097c3230dc1a95f551a3926ce71/common/environment.sls#L35). Instead, I wanna find Couch through Consul (which is already advertising itself https://github.com/PLOS-formulas/lagotto-formula/blob/eea39c588dee4bc5a9d1f95c5ef88b2f6c42aa9d/lagotto/couchdb.sls#L18 )

**Pull request merged**
